version: "3.9"
services:
  db:
    image: "postgres:14.7-alpine3.17"
    restart: always
    container_name: "doc-pgsql-container"
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=doc1-assignment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111

  backend:
    image: 'doc-assignment:v1.1'
    build:
      context: ./
    container_name: 'doc-backend-container'
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://db:5432/doc1-assignment
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  db:
    driver: local